### PR TITLE
Readme Instructions for local build and test

### PR DESCRIPTION
**Pull request by andreazorzetto**
### Description
I've included some simple instructions to build and test the provider locally.

### CODE REVIEW

**Comment by jerbia** [comment]
@mavericknavs can you check why the tests are failing?

**Comment by mavericknavs** [comment]
@jerbia Logs are showing the following error -
provider_test.go:38: AQUA_USER must be set for acceptance tests

The tests should get this value from the secrets which were setup. Can You please confirm if the AQUA_USER, PASSWORD and URL secrets are still present?

**Comment by andreazorzetto** [comment]
That's fine, I'll close this. I hope that maybe my next PRs will make it to the commit history 😉

**Comment by andreazorzetto** [comment]
Closing

**Pull request closed without merging**
