### PR TITLE
Added changes for Registry

### PR DESCRIPTION
**Pull request by mavericknavs**
Made the following changes -

1. Modified provider.go to add Registry resources.
2. Added the following files -
resource_registry.go -> Contains the logic for registry resource. 
resource_registry_test.go -> Contains the tests for registry file 
data_registry.go -> Contains the logic for registry datasource
 data_registry_test.go -> Contains the tests for data_registry file 
client/Registry.go -> The Registry SDK

### CODE REVIEW

**Review by jerbia — CHANGES_REQUESTED** [review]
Can you also add the documentation? There is a "docs" directory, with all the terraform provider data sources and resources. Can you add the registry documentation to there?

**Comment by mavericknavs** [comment]
Docs and Examples Updated. Also I have tested the CRUD operations of the registry and they are working fine.

**Comment by mavericknavs** [comment]
Registry CRUD is working fine but I just noticed there are some issues with data registry

**Comment by jerbia** [comment]
@mavericknavs can you resolve the conflicts? Is it ready to be merged?

**Comment by mavericknavs** [comment]
Hi Amir,
I have resolved the conflicts and also resolved the issue with data_registry.go file. The Matrix tests are failing because the delete user tests are failing. Changes are ready to be merged from my end.

**Comment by mavericknavs** [comment]
@jerbia all Tests have now passed. Can you please merge the PR?

**Review by jerbia — APPROVED** [review]

**Pull request merged**
